version: 0.1.{build}
image: Visual Studio 2017

environment:
  SURGE_TOKEN:
    secure: 63B7vnTM8cXBQOIDUP9JZnBq4H6QCOkuiWX5IsPtpIshzIuK166eGMCtZPXs3+cj
install:
  - docker version
  - npm install -g surge
build_script:
  - ps: Rename-Item -Path ".\app\appsettings.json" -NewName "appsettings.dev.json"
  - ps: Rename-Item -Path ".\app\appsettings.prod.json" -NewName "appsettings.json"
  - docker build -f Dockerfile-windows-deploy -t buildimage .
deploy_script:
  - docker create -it --name buildcontainer buildimage
  - docker cp buildcontainer:/workspace/web-build ./
  - docker rm -f buildcontainer
  - surge --project ./web-build --domain bolaget.surge.sh --token %SURGE_TOKEN%
skip_commits:
  files:
    - '**/*.md'
    - LICENSE
    - '.gitignore'