version: 0.1.{build}
image: Visual Studio 2017

environment:
  SURGE_TOKEN:
    secure: 63B7vnTM8cXBQOIDUP9JZnBq4H6QCOkuiWX5IsPtpIshzIuK166eGMCtZPXs3+cj
install:
  - docker version
build_script:
  - docker build -f Dockerfile-windows-deploy -t surgebuild .
deploy_script:
  - docker run -it surgebuild %SURGE_TOKEN%
skip_commits:
  files:
    - '**/*.md'
    - LICENSE
    - '.gitignore'